trigger: none
#- master

pool:
  vmImage: 'ubuntu-16.04'

container:
    image: amlrpythonmc71c62d90.azurecr.io/mlopsamlsdkforr:latest 
    endpoint: 'amlrpythonmc71c62d90' 

variables:
  #- template: ../../recipes/common/Variables.yml
  - group: MLOPSVG

steps:

  #- task: Bash@3
  #  inputs:
  #    targetType: 'inline'
  #    script: |
  #      Rscript './code/install-packages.R'
  #  displayName: 'Install packages'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        Rscript './code/attrition_model/train-and-register-attritionmodel.R'  --tenant_id $(TENANT_ID) --service_principal_id $(SERVICE_PRINCIPAL_ID) --service_principal_password $(SERVICE_PRINCIPAL_PASSWORD) --aml_workspace $(AML_WORKSPACE) --aml_subscription_id $(AML_SUBSCRIPTION_ID) --aml_resource_group $(AML_RESOURCE_GROUP) --aml_cluster $(AML_CLUSTER)
    displayName: 'Train model'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        Rscript './code/attrition_model/attrition_deploy.R'  --tenant_id $(TENANT_ID) --service_principal_id $(SERVICE_PRINCIPAL_ID) --service_principal_password $(SERVICE_PRINCIPAL_PASSWORD) --aml_workspace $(AML_WORKSPACE) --aml_subscription_id $(AML_SUBSCRIPTION_ID) --aml_resource_group $(AML_RESOURCE_GROUP) --aml_attrition_model $(AML_ATTRITION_MODEL)
    displayName: 'Deploy model'
